[theme]
base = "dark"
primaryColor = "#38bdf8"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e293b"
textColor = "#e2e8f0"
font = "sans serif"

[server]
headless = true
fileWatcherType = "poll"
